name: Bugku签到

# on:
#   schedule:
#     - cron: '0 2 * * *'
on:
  push:
    branches:
      - main

jobs:
  bugku_checkin:
    name: Bugku签到
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码库
        uses: actions/checkout@v2
      
      - name: 设置 Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: 运行 Bugku签到 脚本
        env:
          BUGKU_USERNAME: ${{ secrets.BUGKU_USERNAME }}
          BUGKU_PASSWORD: ${{ secrets.BUGKU_PASSWORD }}
          DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
        run: python Checkin.py
      - name: 运行NSS签到脚本
        env:
          USERNAME2: ${{ secrets.USERNAME2 }}
          PASSWORD2: ${{ secrets.PASSWORD2 }}
          DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
        run: python Checkin2.py
